version: "2"
linters:
  default: all
  disable:
    - prealloc
    - wrapcheck
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
    lll:
      line-length: 120
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - errcheck
        path: _test\.go
        text: Error return value not checked
      - path: (.+)\.go$
        text: ^vendor/
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/yourusername/yourproject
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
